spring:
    profiles:
        active: "@activeEnv@"
    application:
        name: test-gateway

logging:
    level: INFO
    config: classpath:logback.xml

mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        call-setters-on-nulls: true